esphome:
  name: "livingroom-mmwave"
  friendly_name: "livingroom-mmwave"

esp32:
  board: esp32-s2-saola-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  - platform: esphome
    password: !secret password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bathroom-Mmwave Fallback Hotspot"
    password: !secret AP_fallback_password

captive_portal:

uart:
  tx_pin: 18
  rx_pin: 33
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2410:
  
binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target
